LCD_E	BIT	P3.4
	LCD_RS	BIT	P3.5
	LCDADDR	EQU	6000H
	ORG 	2000H
MAIN:
	MOV DPTR,#LCDADDR
	ACALL CLRSCREEN
	ACALL INIT_LCD
	MOV 	R0,#1
    MOV 	R1,#3
	ACALL 	GOTOXY
	ACALL DISPLAYSTRING1
	ACALL  DELAY1S
	ACALL CLRSCREEN
	MOV 	R0,#2
    MOV 	R1,#2
	ACALL 	GOTOXY
	ACALL DISPLAYSTRING2
	ACALL  DELAY1S
	ACALL CLRSCREEN
	ACALL INIT_LCD
	MOV 	R0,#1
    MOV 	R1,#3
	ACALL 	GOTOXY
	ACALL DISPLAYSTRING1
	MOV 	R0,#2
    MOV 	R1,#2
	ACALL 	GOTOXY
	ACALL DISPLAYSTRING2
		
	SJMP  $
CLRSCREEN:
		SETB P3.4
		CLR	P3.5
		MOV	A, #01H
		MOV DPTR,#6000H
		MOVX @DPTR,A
		CLR P3.4
		ACALL	WAIT_LCD 
		RET
INIT_LCD:			  
		MOV	A, #38H		   
		ACALL	WRITECOM
		MOV	A, #0EH		 
		ACALL	WRITECOM
		MOV	A, #06H		 
		ACALL	WRITECOM
		RET
WRITECOM:
		MOV	DPTR, #LCDADDR
		SETB	LCD_E
		CLR		LCD_RS	  
		MOVX	@DPTR, A
		CLR		LCD_E
		ACALL	WAIT_LCD 
		RET
WRITETEXT:
		MOV	DPTR, #LCDADDR
		SETB	LCD_E
		SETB	LCD_RS	  
		MOVX	@DPTR, A
		CLR		LCD_E
		ACALL	WAIT_LCD 
		RET
GOTOXY:
	MOV A,R0
	CJNE A,#1H,HANG2
	MOV A,R1
	ADD A, #80H
    LCALL WRITECOM
       SJMP KT
     HANG2:
       MOV A, R1
       ADD A,#0C0H
       LCALL WRITECOM
   KT: RET
DISPLAYSTRING1:
	MOV A,#0
	LOOP1:
	MOV DPTR,#MESSAGE1
	MOV		R2,A
	MOVC	A,@A+DPTR
	JZ		EXIT1
	ACALL	WRITETEXT
	MOV		A,R2
	INC		A
	DJNZ	B,	LOOP1
	EXIT1:
	RET
DISPLAYSTRING2:
	MOV A,#0
	LOOP2:
	MOV DPTR,#MESSAGE2
	MOV		R2,A
	MOVC	A,@A+DPTR
	JZ		EXIT2
	ACALL	WRITETEXT
	MOV		A,R2
	INC		A
	DJNZ	B,	LOOP2
	EXIT2: RET
WAIT_LCD:		   
	MOV	R6,#10
	DL1:			  
	MOV	R7, #250
	DJNZ	R7, $
	DJNZ	R6,DL1
	RET
DELAY1S:
			MOV 		R7,#8;
LP2:		MOV 		R6,#250;
LP1:		MOV 		R5,#250
			DJNZ 		R5,$;
			DJNZ 		R6, LP1;
			DJNZ 		R7, LP2;
			RET
MESSAGE1: DB "PHUC NGUYEN",0
MESSAGE2: DB "THANH VIEN 2",0
	END
